---
- name: Logstash apt repo
  become: yes
  apt_repository:
    repo: "deb http://packages.elastic.co/logstash/{{ elk_logstash.version }}/debian stable main"
    update_cache: yes

- name: Install logstash apt packages
  become: yes
  apt:
    name: logstash
    state: latest
  notify: restart logstash

- name: Logstash conf file
  become: yes
  template:
    src: "{{ item.src }}"
    dest: /etc/logstash/conf.d/{{ item.dest }}
    owner: root
    group: root
    mode: 644
  with_items: "{{ elk_logstash.configs }}"
  notify: restart logstash

- name: Logstash pattern files
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: /opt/logstash/patterns/{{ item.dest }}
    owner: root
    group: root
    mode: 644
  with_items: "{{ elk_logstash.patterns }}"
  when: elk_logstash.patterns is defined
  notify: restart logstash

- name: plugins | collecting installed plugins
  shell: /opt/logstash/bin/plugin list
  register: logstash_plugins_installed
  always_run: true  #allows checks and diffs to pass

- name: Install logstash plugins
  become: yes
  command: "./bin/plugin install {{ item }}"
  with_items: "{{ elk_logstash.plugins }}"
  when: item not in logstash_plugins_installed.stdout
  args:
    chdir: /opt/logstash
  notify: restart logstash

- name: Update logstash beats plugin
  become: yes
  command: ./bin/plugin update logstash-input-beats
  args:
    chdir: /opt/logstash
  notify: restart logstash

# - name: Supervisor logstash config file
#   become: yes
#   template:
#     src: logstash-supervisor.j2
#     dest: /etc/supervisor/conf.d/logstash.conf
#     owner: root
#     group: root
#     mode: 644
#   notify: restart supervisor

# - name: Make monit to look after Logstash
#   become: yes
#   template: >
#     src: logstash.monitrc.conf.j2
#     dest: /etc/monit/conf.d/logstash.monitrc.conf
#     owner: root
#     group: root
#     mode: 644
#   notify: restart monit
